server:
  port: 9090
spring:
  application:
    name: sae-unsis-fichas
  config:
    import: optional:configserver:http://localhost:8888
  # SpringData
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sae_fichas_db #Cambiar ruta si es necesario
    username: postgres #Cambiar credenciales si es necesario
    password: postgres #Cambiar credenciales si es necesario
  # JPA
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#Conectar con eureka
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
